# <https://bevyengine.org/learn/quick-start/getting-started/setup/#enable-fast-compiles-optional>

[target.x86_64-unknown-linux-gnu]
rustflags = [
  # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
  "-C",
  "link-arg=-fuse-ld=/usr/bin/mold"
]
linker = "clang"

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"
